#ifndef CINEMA_CONSTANTS_H
#define CINEMA_CONSTANTS_H

/* POSIX message queue names must start with '/'. */
#define REQUEST_QUEUE "/cinema_request"
#define CLIENT_QUEUE_PREFIX "/cinema_client_"

#define MAX_SEATS 20
#define MAX_CLIENT_ID 999999

#define COMMAND_SIZE 20
#define QUEUE_NAME_SIZE 64
#define RESPONSE_MESSAGE_SIZE 512
#define INPUT_SIZE 256

#define QUEUE_MAX_MESSAGES 10
#define REQUEST_QUEUE_PERMISSIONS 0660
#define RESPONSE_QUEUE_PERMISSIONS 0600

#define RESPONSE_FAILED 0
#define RESPONSE_SUCCESS 1

#define SERVER_LOCK_FILE "/tmp/cinema_server.lock"

#define DEFAULT_TIMEOUT_SECONDS 10
#define MAX_TIMEOUT_SECONDS 3600
#define TIMEOUT_ENV "CINEMA_TIMEOUT_SECONDS"

#endif
